# Generated by Django 2.0.1 on 2018-01-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('phone_number', models.TextField()),
                ('email', models.TextField()),
                ('role', models.TextField(choices=[('admin', 'Admin'), ('admin', 'Regular')])),
            ],
        ),
    ]
